
alert("Hey")
alert("Do you wanna start?")
let a1 = prompt("Your name")
    a2 = prompt("Middle name")
    a3 = prompt("Last name")
    a4 = prompt("Your hometown")
    a5 = prompt("Do you have high education?")
    a6 = prompt("How old are you?")
    a7 = prompt("Where do live last year (town)?")
    a8 = prompt("Do you have some special skills?")
    a9 = prompt("Your hobbies")
    a10 = prompt("How long have you worked in this sphere?")
    a12 = prompt("Why we should choose you?")
    console.log(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a12)
